# Generated by Django 4.2.7 on 2023-11-05 15:01

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    (
                        "rich_text",
                        wagtail.blocks.RichTextBlock(template="blocks/rich_text.html"),
                    ),
                    (
                        "masthead",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        help_text="An image with dimensions 1900x1216 works best"
                                    ),
                                ),
                                ("content", wagtail.blocks.RichTextBlock()),
                            ]
                        ),
                    ),
                    (
                        "showcase",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "direction",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("left", "Image on Left"),
                                            ("right", "Image on Right"),
                                        ]
                                    ),
                                ),
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                ("title", wagtail.blocks.TextBlock()),
                                ("description", wagtail.blocks.TextBlock()),
                            ]
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
    ]
