version: "3.7"

services:
  nginx:
    build:
      context: .
      dockerfile: ./etc/docker/nginx/Dockerfile
    volumes:
      - staticfiles:/app/static
      - mediafiles:/app/media
    ports:
      - 8001:80
    depends_on:
      - web
    networks:
      # - traefik
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wagtail.rule=Host(`suws-staging.containers-1.sown.org.uk`) || Host(`sown-staging.containers-1.sown.org.uk`) || Host(`cms.containers-1.sown.org.uk`)"
      - "traefik.http.routers.wagtail.tls=true"
      - "traefik.http.routers.wagtail.tls.certresolver=le"
      - "traefik.http.services.wagtail.loadbalancer.server.port=80"
      - "traefik.http.services.wagtail.loadbalancer.server.scheme=http"
      - "traefik.http.services.wagtail.loadbalancer.serverstransport=https_ignore@file"

  web:
    build:
      context: .
      dockerfile: ./etc/docker/web/Dockerfile
    image: kmicms_web
    command: /start
    volumes:
      - staticfiles:/wagtail-static
      - mediafiles:/wagtail-media
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://cache:6379
      - SQL_DATABASE=wagtail
      - SQL_USER=wagtail
      - SQL_PASSWORD=wagtail
      - SQL_HOST=db
      - SQL_PORT=5432
    depends_on:
      - cache
      - db

  cache:
    image: redis:7.2-alpine
    restart: always
    expose:
      - 6379
    volumes: 
      - redis_data:/data

  db:
    image: postgres:16.1-alpine
    restart: always
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=wagtail
      - POSTGRES_USER=wagtail
      - POSTGRES_PASSWORD=wagtail

volumes:
  postgres_data:
  redis_data:
  staticfiles:
  mediafiles:

# networks:
#   traefik:
#     external: true