# Generated by Django 4.2.7 on 2023-11-05 19:40

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
    ]

    operations = [
        migrations.CreateModel(
            name="StandardPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [
                            (
                                "heading",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "size",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("h1", "Heading 1"),
                                                    ("h2", "Heading 2"),
                                                    ("h3", "Heading 3"),
                                                    ("h4", "Heading 4"),
                                                ]
                                            ),
                                        ),
                                        ("text", wagtail.blocks.TextBlock()),
                                    ]
                                ),
                            ),
                            (
                                "rich_text",
                                wagtail.blocks.RichTextBlock(editor="all-but-headings"),
                            ),
                        ],
                        use_json_field=True,
                    ),
                ),
                (
                    "show_breadcrumbs",
                    models.BooleanField(
                        default=True, help_text="Show breadcrumbs at top of page?"
                    ),
                ),
                (
                    "show_title",
                    models.BooleanField(
                        default=True, help_text="Show page title at top of page?"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
