# Generated by Django 4.2.10 on 2024-02-10 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0091_remove_revision_submitted_for_moderation"),
        ("infra", "0002_use_streamfield_on_infra_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="NetboxEntityPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("netbox_name", models.CharField(max_length=255)),
                ("netbox_id", models.IntegerField(verbose_name="Netbox ID")),
                (
                    "netbox_entity_type",
                    models.CharField(
                        choices=[("DEV", "Physical Device"), ("VM", "Virtual Machine")],
                        max_length=3,
                    ),
                ),
                ("netbox_data", models.JSONField()),
            ],
            options={
                "verbose_name": "Netbox Entity Page",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.AlterModelOptions(
            name="netboxinfrastructurepage",
            options={"verbose_name": "Netbox Index Page"},
        ),
        migrations.RemoveField(
            model_name="netboxinfrastructurepage",
            name="device_description",
        ),
        migrations.RemoveField(
            model_name="netboxinfrastructurepage",
            name="vm_description",
        ),
        migrations.AddConstraint(
            model_name="netboxentitypage",
            constraint=models.UniqueConstraint(
                fields=("netbox_id", "netbox_entity_type"),
                name="unique_id_for_netbox_entity",
            ),
        ),
    ]
