#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python /app/sowncms/manage.py collectstatic --noinput
python /app/sowncms/manage.py migrate

/usr/local/bin/gunicorn sowncms.wsgi:application --bind 0.0.0.0:8000 --chdir=/app/sowncms