# Generated by Django 4.2.7 on 2023-11-17 00:10

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMediaAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("discord", "Discord"),
                            ("facebook", "Facebook"),
                            ("github", "GitHub"),
                            ("mastodon", "Mastodon"),
                            ("snapchat", "Snapchat"),
                            ("tiktok", "TikTok"),
                            ("twitter", "Twitter / X"),
                            ("whatsapp", "WhatsApp"),
                            ("youtube", "YouTube"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField()),
                (
                    "site_settings",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_media_accounts",
                        to="core.sitesettings",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
