# Generated by Django 4.2.7 on 2023-12-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_discordaccount_discordconnection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discordaccount",
            name="discord_id",
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
