# Generated by Django 4.2.10 on 2024-02-10 14:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_discord_accounts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discordconnection",
            name="discord_account",
        ),
        migrations.RemoveField(
            model_name="discordconnection",
            name="user",
        ),
        migrations.DeleteModel(
            name="DiscordAccount",
        ),
        migrations.DeleteModel(
            name="DiscordConnection",
        ),
    ]
