# Generated by Django 4.2.7 on 2023-11-16 19:29

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
    ]

    operations = [
        migrations.CreateModel(
            name="NavigationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "main_menu",
                    wagtail.fields.StreamField(
                        [
                            (
                                "page_link",
                                wagtail.blocks.StructBlock(
                                    [("page", wagtail.blocks.PageChooserBlock())],
                                ),
                            ),
                            (
                                "external_link",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "label",
                                            wagtail.blocks.CharBlock(
                                                label="Label", max_length=55,
                                            ),
                                        ),
                                        ("url", wagtail.blocks.URLBlock(label="URL")),
                                    ],
                                ),
                            ),
                        ],
                        use_json_field=True,
                    ),
                ),
                (
                    "footer_menu",
                    wagtail.fields.StreamField(
                        [
                            (
                                "page_link",
                                wagtail.blocks.StructBlock(
                                    [("page", wagtail.blocks.PageChooserBlock())],
                                ),
                            ),
                            (
                                "external_link",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "label",
                                            wagtail.blocks.CharBlock(
                                                label="Label", max_length=55,
                                            ),
                                        ),
                                        ("url", wagtail.blocks.URLBlock(label="URL")),
                                    ],
                                ),
                            ),
                        ],
                        use_json_field=True,
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
